# 1. set Rust official image
FROM rust

# 2. Copy the files in your machine to the Docker image
COPY ./ ./

# Build for release
RUN cargo build --release

# Run the binary
ENTRYPOINT ["./target/release/my-decoder"]

CMD [""]
